# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dbmanager_pb2 as dbmanager__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dbmanager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DbmanagerStub(object):
    """── Service Definition ─────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTenantSchema = channel.unary_unary(
                '/dbmanager.Dbmanager/CreateTenantSchema',
                request_serializer=dbmanager__pb2.CreateSchemaRequest.SerializeToString,
                response_deserializer=dbmanager__pb2.CreateSchemaResponse.FromString,
                _registered_method=True)
        self.DeleteTenantSchema = channel.unary_unary(
                '/dbmanager.Dbmanager/DeleteTenantSchema',
                request_serializer=dbmanager__pb2.DeleteSchemaRequest.SerializeToString,
                response_deserializer=dbmanager__pb2.DeleteSchemaResponse.FromString,
                _registered_method=True)
        self.GetTelemetry = channel.unary_unary(
                '/dbmanager.Dbmanager/GetTelemetry',
                request_serializer=dbmanager__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=dbmanager__pb2.TelemetryResponse.FromString,
                _registered_method=True)
        self.GetTenantStats = channel.unary_unary(
                '/dbmanager.Dbmanager/GetTenantStats',
                request_serializer=dbmanager__pb2.TenantStatsRequest.SerializeToString,
                response_deserializer=dbmanager__pb2.TenantStatsResponse.FromString,
                _registered_method=True)
        self.InitializeDatabase = channel.unary_unary(
                '/dbmanager.Dbmanager/InitializeDatabase',
                request_serializer=dbmanager__pb2.CreateSchemaRequest.SerializeToString,
                response_deserializer=dbmanager__pb2.CreateSchemaResponse.FromString,
                _registered_method=True)


class DbmanagerServicer(object):
    """── Service Definition ─────────────────────────────────────────
    """

    def CreateTenantSchema(self, request, context):
        """Called when a new tenant signs up
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTenantSchema(self, request, context):
        """Called when a tenant is deleted
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelemetry(self, request, context):
        """Called by telemetry layer to get live DB stats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenantStats(self, request, context):
        """Called to get per-tenant schema size + connection count
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeDatabase(self, request, context):
        """Canonical name (UML). Alias of CreateTenantSchema — same request/response + handler.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DbmanagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTenantSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTenantSchema,
                    request_deserializer=dbmanager__pb2.CreateSchemaRequest.FromString,
                    response_serializer=dbmanager__pb2.CreateSchemaResponse.SerializeToString,
            ),
            'DeleteTenantSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTenantSchema,
                    request_deserializer=dbmanager__pb2.DeleteSchemaRequest.FromString,
                    response_serializer=dbmanager__pb2.DeleteSchemaResponse.SerializeToString,
            ),
            'GetTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetry,
                    request_deserializer=dbmanager__pb2.TelemetryRequest.FromString,
                    response_serializer=dbmanager__pb2.TelemetryResponse.SerializeToString,
            ),
            'GetTenantStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenantStats,
                    request_deserializer=dbmanager__pb2.TenantStatsRequest.FromString,
                    response_serializer=dbmanager__pb2.TenantStatsResponse.SerializeToString,
            ),
            'InitializeDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeDatabase,
                    request_deserializer=dbmanager__pb2.CreateSchemaRequest.FromString,
                    response_serializer=dbmanager__pb2.CreateSchemaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbmanager.Dbmanager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dbmanager.Dbmanager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Dbmanager(object):
    """── Service Definition ─────────────────────────────────────────
    """

    @staticmethod
    def CreateTenantSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbmanager.Dbmanager/CreateTenantSchema',
            dbmanager__pb2.CreateSchemaRequest.SerializeToString,
            dbmanager__pb2.CreateSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTenantSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbmanager.Dbmanager/DeleteTenantSchema',
            dbmanager__pb2.DeleteSchemaRequest.SerializeToString,
            dbmanager__pb2.DeleteSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbmanager.Dbmanager/GetTelemetry',
            dbmanager__pb2.TelemetryRequest.SerializeToString,
            dbmanager__pb2.TelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTenantStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbmanager.Dbmanager/GetTenantStats',
            dbmanager__pb2.TenantStatsRequest.SerializeToString,
            dbmanager__pb2.TenantStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitializeDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dbmanager.Dbmanager/InitializeDatabase',
            dbmanager__pb2.CreateSchemaRequest.SerializeToString,
            dbmanager__pb2.CreateSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
