apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: intellidb
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_ME"
  REPLICATION_PASSWORD: "CHANGE_ME"
  PATRONI_SUPERUSER_PASSWORD: "CHANGE_ME"
  PATRONI_REPLICATION_PASSWORD: "CHANGE_ME"